# Generated by Django 2.0.6 on 2018-06-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='temp_tour18',
            field=models.BooleanField(default=False),
        ),
    ]
