# Generated by Django 2.0.8 on 2018-09-02 17:17

import blapp.utils.db_fields
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [("people", "0002_person_temp_tour18")]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    blapp.utils.db_fields.PrimaryKeyUUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    blapp.utils.db_fields.NameField(
                        max_length=256, verbose_name="name"
                    ),
                ),
                (
                    "description",
                    blapp.utils.db_fields.DescriptionField(
                        blank=True, verbose_name="description"
                    ),
                ),
                ("membership", models.BooleanField(default=False)),
                ("engagement", models.BooleanField(default=False)),
                ("legacy_table", models.CharField(max_length=64)),
                ("legacy_id", models.CharField(max_length=64)),
                ("lft", models.PositiveIntegerField(db_index=True, editable=False)),
                ("rght", models.PositiveIntegerField(db_index=True, editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(db_index=True, editable=False)),
                (
                    "parent",
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="people.Role",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="RoleAssignment",
            fields=[
                (
                    "id",
                    blapp.utils.db_fields.PrimaryKeyUUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period",
                    django.contrib.postgres.fields.ranges.DateRangeField(
                        verbose_name="period"
                    ),
                ),
                ("trial", models.BooleanField()),
                ("legacy_table", models.CharField(max_length=64)),
                ("legacy_start_id", models.CharField(max_length=64)),
                ("legacy_end_id", models.CharField(max_length=64)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_assignments",
                        to="people.Person",
                        verbose_name="person",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_assignments",
                        to="people.Role",
                        verbose_name="role",
                    ),
                ),
            ],
        ),
    ]
