# Generated by Django 3.2.14 on 2022-07-24 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_auto_20180903_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
