# Generated by Django 4.1 on 2022-11-01 13:35

import blapp.utils.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0005_auto_20220724_0253"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="arbitrary_text",
            field=blapp.utils.db_fields.DescriptionField(
                blank=True, verbose_name="arbitrary text"
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="country",
            field=blapp.utils.db_fields.NameField(
                blank=True, max_length=256, verbose_name="country"
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="dietary_preferences",
            field=blapp.utils.db_fields.NameField(
                blank=True, max_length=256, verbose_name="dietary preferences"
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="national_id_number",
            field=models.CharField(
                blank=True, max_length=4, verbose_name="national id number"
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="phone_number_1",
            field=blapp.utils.db_fields.PhoneNumberField(
                blank=True, max_length=30, verbose_name="phone number 1"
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="phone_number_1_label",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="phone number 1 label"
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="phone_number_2",
            field=blapp.utils.db_fields.PhoneNumberField(
                blank=True, max_length=30, verbose_name="phone number 2"
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="phone_number_2_label",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="phone number 2 label"
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="phone_number_3",
            field=blapp.utils.db_fields.PhoneNumberField(
                blank=True, max_length=30, verbose_name="phone number 3"
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="phone_number_3_label",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="phone number 3 label"
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="postal_code",
            field=models.CharField(
                blank=True, max_length=7, verbose_name="postal code"
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="postal_region",
            field=blapp.utils.db_fields.NameField(
                blank=True, max_length=256, verbose_name="postal region"
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="street_address",
            field=blapp.utils.db_fields.NameField(
                blank=True, max_length=256, verbose_name="street address"
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="student_id",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="student id"
            ),
        ),
    ]
