# Generated by Django 4.1 on 2022-09-01 00:08

import blapp.utils.db_fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0005_auto_20220724_0253"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="arbitrary_text",
            field=blapp.utils.db_fields.DescriptionField(
                blank=True, verbose_name="arbitrary text"
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="country",
            field=blapp.utils.db_fields.NameField(
                blank=True, max_length=256, verbose_name="country"
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="dietary_preferences",
            field=blapp.utils.db_fields.NameField(
                blank=True, max_length=256, verbose_name="dietary preferences"
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="national_id_number",
            field=models.CharField(
                blank=True, max_length=4, verbose_name="national id number"
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="postal_code",
            field=models.CharField(
                blank=True, max_length=7, verbose_name="postal code"
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="postal_region",
            field=blapp.utils.db_fields.NameField(
                blank=True, max_length=256, verbose_name="postal region"
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="street_address",
            field=blapp.utils.db_fields.NameField(
                blank=True, max_length=256, verbose_name="street address"
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="student_id",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="student id"
            ),
        ),
        migrations.CreateModel(
            name="PhoneNumber",
            fields=[
                (
                    "id",
                    blapp.utils.db_fields.PrimaryKeyUUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=20, verbose_name="label")),
                (
                    "phone_number",
                    models.CharField(max_length=14, verbose_name="phone number"),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phone_numbers",
                        to="people.person",
                        verbose_name="person",
                    ),
                ),
            ],
        ),
    ]
