# Generated by Django 4.1 on 2022-08-30 22:29

import blapp.utils.db_fields
from django.db import migrations, models
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0005_auto_20220724_0253"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="arbitrary_text",
            field=blapp.utils.db_fields.DescriptionField(
                blank=True, verbose_name="arbitrary text"
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="country",
            field=blapp.utils.db_fields.NameField(
                blank=True, max_length=256, verbose_name="country"
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="dietary_preferences",
            field=blapp.utils.db_fields.NameField(
                blank=True, max_length=256, verbose_name="dietary preferences"
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="national_id_number",
            field=models.CharField(
                blank=True, max_length=4, verbose_name="national id number"
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="phone_numbers",
            field=django_jsonform.models.fields.ArrayField(
                base_field=models.CharField(max_length=14),
                blank=True,
                default=list,
                size=3,
                verbose_name="phone numbers",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="postal_code",
            field=models.CharField(
                blank=True, max_length=7, verbose_name="postal code"
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="postal_region",
            field=blapp.utils.db_fields.NameField(
                blank=True, max_length=256, verbose_name="postal region"
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="street_address",
            field=blapp.utils.db_fields.NameField(
                blank=True, max_length=256, verbose_name="street address"
            ),
        ),
    ]
