# Generated by Django 4.1 on 2022-08-31 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0005_auto_20220724_0253"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="roleassignment",
            options={"ordering": ["start_date_time"]},
        ),
        migrations.RemoveField(
            model_name="roleassignment",
            name="period",
        ),
        migrations.AddField(
            model_name="person",
            name="arbitrary_text",
            field=models.TextField(blank=True, verbose_name="arbitrary text"),
        ),
        migrations.AddField(
            model_name="person",
            name="country",
            field=models.CharField(blank=True, max_length=63, verbose_name="country"),
        ),
        migrations.AddField(
            model_name="person",
            name="home_address",
            field=models.CharField(
                blank=True, max_length=63, verbose_name="home address"
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="organ_donor",
            field=models.BooleanField(default=False, verbose_name="organ donator"),
        ),
        migrations.AddField(
            model_name="person",
            name="organ_donor_until",
            field=models.DateField(
                blank=True, null=True, verbose_name="organ donor until"
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=31, verbose_name="phone number"
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="postal_code",
            field=models.CharField(
                blank=True, max_length=15, verbose_name="postal code"
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="postal_region",
            field=models.CharField(
                blank=True, max_length=63, verbose_name="postal region"
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="student_id",
            field=models.CharField(blank=True, max_length=8, verbose_name="student id"),
        ),
        migrations.AddField(
            model_name="person",
            name="work",
            field=models.CharField(blank=True, max_length=63, verbose_name="work"),
        ),
        migrations.AddField(
            model_name="roleassignment",
            name="end_date_time",
            field=models.DateField(blank=True, null=True, verbose_name="end date"),
        ),
        migrations.AddField(
            model_name="roleassignment",
            name="start_date_time",
            field=models.DateField(blank=True, null=True, verbose_name="start date"),
        ),
    ]
