# Generated by Django 4.1 on 2022-09-08 18:37

import blapp.utils.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0006_person_arbitrary_text_person_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="organ_donor",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="person",
            name="organ_donor_until",
            field=models.DateField(
                blank=True, null=True, verbose_name="organ donor until"
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="work_name",
            field=blapp.utils.db_fields.NameField(
                blank=True, max_length=256, verbose_name="work"
            ),
        ),
    ]
