# Generated by Django 4.1.3 on 2023-03-03 20:50

import blapp.utils.db_fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0006_person_arbitrary_text_person_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', blapp.utils.db_fields.PrimaryKeyUUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', blapp.utils.db_fields.PrimaryKeyUUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', blapp.utils.db_fields.NameField(max_length=256, verbose_name='header')),
                ('description', blapp.utils.db_fields.DescriptionField(blank=True, verbose_name='description')),
                ('location', blapp.utils.db_fields.NameField(max_length=256, verbose_name='location')),
                ('start_date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='start date time')),
                ('end_date_time', models.DateTimeField(verbose_name='end date time')),
                ('attendants', models.ManyToManyField(related_name='attendants', through='events.Attendance', to='people.person')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='people.person', verbose_name='owner')),
            ],
            options={
                'ordering': ('start_date_time', 'header'),
            },
        ),
        migrations.AddField(
            model_name='attendance',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.person'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(check=models.Q(('end_date_time__gt', models.F('start_date_time'))), name='event_end_date_time_gt_start_date_time'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('event', 'person'), name='unique_attendant'),
        ),
    ]
