# Generated by Django 3.2.7 on 2022-01-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='comment'),
        ),
        migrations.AddField(
            model_name='event',
            name='contact_mail',
            field=models.TextField(blank=True, null=True, verbose_name='contact mail'),
        ),
        migrations.AddField(
            model_name='event',
            name='contact_phone',
            field=models.TextField(blank=True, null=True, verbose_name='contact phone'),
        ),
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.TextField(blank=True, null=True, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='event',
            name='rating',
            field=models.TextField(blank=True, null=True, verbose_name='rating'),
        ),
    ]
