# Generated by Django 3.2.7 on 2022-01-22 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='contact_info',
            field=models.TextField(blank=True, null=True, verbose_name='contact information'),
        ),
    ]
