# Generated by Django 4.1 on 2022-08-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="comment",
            field=models.TextField(blank=True, null=True, verbose_name="comment"),
        ),
        migrations.AddField(
            model_name="event",
            name="contact_mail",
            field=models.TextField(
                blank=True, null=True, verbose_name="contact mail information"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="price",
            field=models.TextField(blank=True, null=True, verbose_name="price"),
        ),
        migrations.AddField(
            model_name="event",
            name="rating",
            field=models.TextField(blank=True, null=True, verbose_name="rating"),
        ),
    ]
