# Generated by Django 3.2.7 on 2022-03-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20220122_1547'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('event', 'person'), name='unique-attendant'),
        ),
    ]
