# Generated by Django 3.2.7 on 2022-01-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_contact_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='contact_info',
        ),
        migrations.AddField(
            model_name='event',
            name='contact_person',
            field=models.TextField(blank=True, null=True, verbose_name='contact person information'),
        ),
    ]
