# Generated by Django 4.1 on 2022-08-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_event_comment_event_contact_mail_event_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="contact_phone",
            field=models.TextField(
                blank=True, null=True, verbose_name="contact phone information"
            ),
        ),
    ]
