version: '3.6'

services:
  selenium:
    image: selenium/standalone-firefox:110.0
    shm_size: 2gb

  app: &app
    image: quay.io/litheblas/blapp:latest
    build:
      context: .
    environment:
      BLAPP_ALLOWED_HOSTS: '*'
      BLAPP_DATABASE_URL: &database_url postgres://blapp:test@postgres:5432/blapp
      BLAPP_TEST_DATABASE_URL: *database_url
      BLAPP_LEGACY_DATABASE_URL: sqlite:////
      BLAPP_DEBUG_MODE: 'false'
      BLAPP_EMAIL_URL: consolemail://
      BLAPP_REDIS_URL: redis://redis:6379/0
      BLAPP_SECRET_KEY: test
      BLAPP_SECURE_PROXY_HEADER: HTTP_X_FORWARDED_PROTO=https
      BLAPP_TEST_MODE: 'true'
      BLAPP_TEST_SELENIUM_URL: http://selenium:4444/wd/hub
      BLAPP_TEST_WEBSERVER_URL: http://app
    depends_on:
      - postgres
      - redis

  tests:
    <<: *app
    image: quay.io/litheblas/blapp:latest-dev
    build:
      context: .
      args:
        with_dev_packages: 'true'
    depends_on:
      - app
      - postgres
      - selenium
      - redis
    command: pipenv run docker-test

  postgres:
    image: postgres:15.2-alpine
    environment:
      - 'POSTGRES_USER=blapp'
      - 'POSTGRES_PASSWORD=test'
    volumes:
      - type: tmpfs
        target: /var/lib/postgresql/data

  redis:
    image: redis:7.0.9-alpine
    volumes:
      - type: tmpfs
        target: /data
