# Generated by Django 2.0.6 on 2018-06-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("blapp_auth", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="serviceaccount",
            name="token",
            field=models.CharField(editable=False, max_length=40),
        )
    ]
