name: Docker Image CI

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - uses: actions/checkout@v3
    - name: Build Docker image and run tests
      run: |
        docker compose -f ./docker-compose.ci.yml build
        docker compose -f ./docker-compose.ci.yml run tests
    - name: Push to DockerHub
      uses: docker/build-push-action@v4.0.0
      with:
        push: true
        tags: oscarfalk/blapp:latest
