# Generated by Django 4.1 on 2022-08-29 23:37

import blapp.utils.db_fields
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Show",
            fields=[
                (
                    "id",
                    blapp.utils.db_fields.PrimaryKeyUUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "header",
                    blapp.utils.db_fields.NameField(
                        max_length=256, verbose_name="header"
                    ),
                ),
                (
                    "description",
                    blapp.utils.db_fields.DescriptionField(
                        blank=True, verbose_name="description"
                    ),
                ),
                (
                    "start_date_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="start date time",
                    ),
                ),
                ("end_date_time", models.DateTimeField(verbose_name="end date time")),
                (
                    "location",
                    blapp.utils.db_fields.NameField(
                        max_length=256, verbose_name="location"
                    ),
                ),
                (
                    "driving_section",
                    blapp.utils.db_fields.NameField(
                        blank=True, max_length=256, verbose_name="driving section"
                    ),
                ),
                (
                    "contact_person_name",
                    blapp.utils.db_fields.NameField(
                        blank=True, max_length=256, verbose_name="contact person name"
                    ),
                ),
                (
                    "contact_person_email_address",
                    blapp.utils.db_fields.NameField(
                        blank=True,
                        max_length=256,
                        verbose_name="contact person email address",
                    ),
                ),
                (
                    "contact_person_phone_number",
                    blapp.utils.db_fields.NameField(
                        blank=True,
                        max_length=256,
                        verbose_name="contact person phone number",
                    ),
                ),
                (
                    "contact_person_comment",
                    blapp.utils.db_fields.DescriptionField(
                        blank=True, verbose_name="contact person comment"
                    ),
                ),
                (
                    "comment",
                    blapp.utils.db_fields.DescriptionField(
                        blank=True, verbose_name="comment"
                    ),
                ),
                (
                    "fee",
                    blapp.utils.db_fields.NameField(
                        blank=True, max_length=256, verbose_name="fee"
                    ),
                ),
            ],
            options={
                "ordering": ("start_date_time", "header"),
            },
        ),
        migrations.AddConstraint(
            model_name="show",
            constraint=models.CheckConstraint(
                check=models.Q(("end_date_time__gt", models.F("start_date_time"))),
                name="show_end_date_time_gt_start_date_time",
            ),
        ),
    ]
