# Generated by Django 4.1 on 2022-08-29 18:26

import blapp.utils.db_fields
import datetime
import django.contrib.postgres.fields.ranges
from django.db import migrations
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Show",
            fields=[
                (
                    "id",
                    blapp.utils.db_fields.PrimaryKeyUUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "header",
                    blapp.utils.db_fields.NameField(
                        max_length=256, verbose_name="header"
                    ),
                ),
                (
                    "description",
                    blapp.utils.db_fields.DescriptionField(
                        blank=True, verbose_name="description"
                    ),
                ),
                (
                    "date_time",
                    django.contrib.postgres.fields.ranges.DateTimeRangeField(
                        default=(
                            datetime.datetime(2022, 8, 29, 18, 26, 0, 315615),
                            datetime.datetime(2022, 8, 29, 19, 26, 0, 315622),
                        ),
                        verbose_name="date and time",
                    ),
                ),
                (
                    "location",
                    blapp.utils.db_fields.NameField(
                        max_length=256, verbose_name="location"
                    ),
                ),
                (
                    "driving_section",
                    blapp.utils.db_fields.NameField(
                        blank=True, max_length=256, verbose_name="driving section"
                    ),
                ),
                (
                    "contact_person_name",
                    blapp.utils.db_fields.NameField(
                        blank=True, max_length=256, verbose_name="contact person name"
                    ),
                ),
                (
                    "contact_person_email_address",
                    blapp.utils.db_fields.NameField(
                        blank=True,
                        max_length=256,
                        verbose_name="contact person email address",
                    ),
                ),
                (
                    "contact_person_phone_number",
                    blapp.utils.db_fields.NameField(
                        blank=True,
                        max_length=256,
                        verbose_name="contact person phone number",
                    ),
                ),
                (
                    "fee",
                    blapp.utils.db_fields.NameField(
                        blank=True, max_length=256, verbose_name="fee"
                    ),
                ),
            ],
            options={
                "ordering": ("date_time", "header"),
            },
        ),
    ]
