# Generated by Django 4.1 on 2022-08-31 18:16

import blapp.utils.db_fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("people", "0005_auto_20220724_0253"),
        ("shows", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    blapp.utils.db_fields.PrimaryKeyUUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="show",
            name="driving_section",
        ),
        migrations.RemoveField(
            model_name="show",
            name="fee",
        ),
        migrations.AddField(
            model_name="show",
            name="attendants",
            field=models.ManyToManyField(
                related_name="attendants",
                through="shows.Attendance",
                to="people.person",
            ),
        ),
        migrations.AddField(
            model_name="show",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="event_creator",
                to=settings.AUTH_USER_MODEL,
                verbose_name="event creator",
            ),
        ),
        migrations.AddField(
            model_name="show",
            name="obligatory",
            field=models.BooleanField(
                default=True, verbose_name="obligatory attendance"
            ),
        ),
        migrations.AddField(
            model_name="show",
            name="price",
            field=blapp.utils.db_fields.NameField(
                blank=True, max_length=256, verbose_name="price"
            ),
        ),
        migrations.AddField(
            model_name="show",
            name="published",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="show",
            name="rating",
            field=models.TextField(blank=True, null=True, verbose_name="rating"),
        ),
        migrations.AddField(
            model_name="show",
            name="responsible_group",
            field=blapp.utils.db_fields.NameField(
                blank=True, max_length=256, verbose_name="responsible group"
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="shows.show"
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="people.person"
            ),
        ),
    ]
